language: node_js
matrix:
  include:
    - node_js: 14
    - node_js: 12
    - node_js: 10
  allow_failures:
    - node_js: 12
    - node_js: 10
install:
  - npm install
  - npm install --only=dev
script:
  - npm test
  - npm run coverage
  - npm run build
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
  - alpha
  - beta
